name: "Build NishBox"

on:
  workflow_dispatch:
    inputs:
      release:
        description: "release or not"
        type: boolean
        default: true
        required: true

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build-win32:
    name: "Build for Windows 32-bit"
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: "true"
    - name: Install packages
      run: sudo apt-get install mingw-w64
    - name: Run build script
      run: env ARCH=i686 BITS=32 MAKE=make ./tool/build-windows.sh
