name: "Build NishBox"

on:
  workflow_dispatch:
    inputs:
      release:
        description: "release or not"
        type: boolean
        default: true
        required: true
  push:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build-win32:
    name: "Build for Windows 32-bit"
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install mingw-w64
    - name: Get and extract ODE
      run: wget https://sourceforge.net/projects/opende/files/ODE/0.13/ode-0.13.tar.gz/download -O - | tar xvzf -
    - name: Build ODE
      run: cd ode-0.13 && ./configure --host=i686-w64-mingw32 --prefix=/ --disable-demos --without-drawstuff --enable-shared && make
    - name: Install ODE
      run: make -C ode-0.13 install DESTDIR=`pwd`/deps
